---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: imagegenapi
  annotations:
    applications.app.bytetrade.io/gpu-inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagegenapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: imagegenapi
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: imagegenapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: imagegenapi-config
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            requests:
              cpu: "4"
              memory: 12Gi
              nvidia.com/gpu: "1"
              nvidia.com/gpumem: "12288"
            limits:
              cpu: "4"
              memory: 12Gi
              nvidia.com/gpu: "1"
              nvidia.com/gpumem: "12288"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 5
          volumeMounts:
            - name: huggingface
              mountPath: /data/huggingface
            - name: torch
              mountPath: /data/torch
            - name: outputs
              mountPath: /data/outputs
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
        - name: huggingface
          hostPath:
            {{- if .Values.sysVersion }}
              {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: "{{ .Values.userspace.appData }}/huggingface"
              {{- else }}
            path: "{{ .Values.userspace.appData }}/{{ .Release.Name }}/huggingface"
              {{- end }}
            {{- else }}
            path: "{{ .Values.userspace.appData }}/{{ .Release.Name }}/huggingface"
            {{- end }}
            type: DirectoryOrCreate
        - name: torch
          hostPath:
            {{- if .Values.sysVersion }}
              {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: "{{ .Values.userspace.appData }}/torch"
              {{- else }}
            path: "{{ .Values.userspace.appData }}/{{ .Release.Name }}/torch"
              {{- end }}
            {{- else }}
            path: "{{ .Values.userspace.appData }}/{{ .Release.Name }}/torch"
            {{- end }}
            type: DirectoryOrCreate
        - name: outputs
          hostPath:
            {{- if .Values.sysVersion }}
              {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: "{{ .Values.userspace.appData }}/outputs"
              {{- else }}
            path: "{{ .Values.userspace.appData }}/{{ .Release.Name }}/outputs"
              {{- end }}
            {{- else }}
            path: "{{ .Values.userspace.appData }}/{{ .Release.Name }}/outputs"
            {{- end }}
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: imagegenapi-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: imagegenapi
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
